// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Css from "@emotion/css";

var footerWrapper = Css.css("\nbackground: gray;\n");

export {
  footerWrapper ,
  
}
/* footerWrapper Not a pure module */
