// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as FooterStyles from "./FooterStyles.js";

function Footer(Props) {
  return React.createElement("footer", {
              className: FooterStyles.footerWrapper
            }, "Footer Component");
}

var make = Footer;

export {
  make ,
  
}
/* react Not a pure module */
