// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Css from "@emotion/css";

var layoutContainer = Css.css("\n  display: flex;\n  min-height: 100vh;\n  flex-direction: column;\n");

export {
  layoutContainer ,
  
}
/* layoutContainer Not a pure module */
