// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Footer from "../Footer/Footer.js";
import * as Navbar from "../Navbar/Navbar.js";
import * as LayoutStyles from "./LayoutStyles.js";

function Layout$Layout(Props) {
  var children = Props.children;
  return React.createElement("div", {
              className: LayoutStyles.layoutContainer
            }, React.createElement(Navbar.make, {}), children, React.createElement(Footer.make, {}));
}

var Layout = {
  make: Layout$Layout
};

export {
  Layout ,
  
}
/* react Not a pure module */
