// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Switchback(Props) {
  return React.createElement("div", undefined, "switchback component");
}

var make = Switchback;

export {
  make ,
  
}
/* react Not a pure module */
