// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ApolloClient from "rescript-apollo-client/lib/es6/src/ApolloClient.js";
import * as ApolloClient__Cache_InMemory_InMemoryCache from "rescript-apollo-client/lib/es6/src/@apollo/client/cache/inmemory/ApolloClient__Cache_InMemory_InMemoryCache.js";

var client = ApolloClient.make((function (param) {
        return "https://graphql.org/swap-graphql";
      }), undefined, undefined, undefined, ApolloClient__Cache_InMemory_InMemoryCache.make(undefined, undefined, undefined, undefined, undefined, undefined), undefined, undefined, true, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);

export {
  client ,
  
}
/* client Not a pure module */
