// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Home from "./Home.js";
import * as React from "react";
import * as Switchback from "./components/Switchback.js";
import * as PageNotFound from "./PageNotFound.js";
import * as RescriptReactRouter from "@rescript/react/lib/es6/src/RescriptReactRouter.js";

function App$App(Props) {
  var url = RescriptReactRouter.useUrl(undefined, undefined);
  var match = url.path;
  if (!match) {
    return React.createElement(Home.make, {});
  }
  var exit = 0;
  switch (match.hd) {
    case "home" :
        if (!match.tl) {
          return React.createElement(Home.make, {});
        }
        break;
    case "about" :
    case "user" :
        exit = 2;
        break;
    default:
      
  }
  if (exit === 2 && !match.tl) {
    return React.createElement(Switchback.make, {});
  }
  return React.createElement(PageNotFound.make, {});
}

var App = {
  make: App$App
};

export {
  App ,
  
}
/* Home Not a pure module */
