// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Home from "./pages/Home.js";
import * as About from "./pages/About.js";
import * as React from "react";
import * as Writing from "./pages/Writing.js";
import * as PageNotFound from "./pages/PageNotFound.js";
import * as RescriptReactRouter from "@rescript/react/lib/es6/src/RescriptReactRouter.js";

function App$App(Props) {
  var url = RescriptReactRouter.useUrl(undefined, undefined);
  var match = url.path;
  if (!match) {
    return React.createElement(Home.make, {});
  }
  switch (match.hd) {
    case "about" :
        if (!match.tl) {
          return React.createElement(About.make, {});
        }
        break;
    case "home" :
        if (!match.tl) {
          return React.createElement(Home.make, {});
        }
        break;
    case "writing" :
        if (!match.tl) {
          return React.createElement(Writing.make, {});
        }
        break;
    default:
      
  }
  return React.createElement(PageNotFound.make, {});
}

var App = {
  make: App$App
};

export {
  App ,
  
}
/* Home Not a pure module */
