// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function App$App(Props) {
  return React.createElement("div", undefined, "testing");
}

var App = {
  make: App$App
};

export {
  App ,
  
}
/* react Not a pure module */
