// Generated by ReScript, PLEASE EDIT WITH CARE

import * as App from "./App.js";
import * as React from "react";
import * as ReactDom from "react-dom";

var root = document.querySelector("#root");

if (!(root == null)) {
  ReactDom.render(React.createElement(App.App.make, {}), root);
}

export {
  
}
/* root Not a pure module */
