// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Layout from "../components/Layout.js";

function About(Props) {
  return React.createElement(Layout.Layout.make, {
              children: React.createElement("div", undefined, "about page")
            });
}

var make = About;

export {
  make ,
  
}
/* react Not a pure module */
