// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Layout from "../components/Layout/Layout.js";

function Home(Props) {
  return React.createElement(Layout.Layout.make, {
              children: React.createElement("div", undefined, "Home page")
            });
}

var make = Home;

export {
  make ,
  
}
/* react Not a pure module */
