// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function PageNotFound(Props) {
  return React.createElement("div", undefined, "page not found");
}

var make = PageNotFound;

export {
  make ,
  
}
/* react Not a pure module */
