// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Layout from "../components/Layout/Layout.js";

function Writing(Props) {
  return React.createElement(Layout.Layout.make, {
              children: "writing page. will have stuff from api here: "
            });
}

var make = Writing;

export {
  make ,
  
}
/* react Not a pure module */
