// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Navbar from "./Navbar/Navbar.js";

function Layout$Layout(Props) {
  var children = Props.children;
  return React.createElement("div", undefined, React.createElement(Navbar.make, {}), children);
}

var Layout = {
  make: Layout$Layout
};

export {
  Layout ,
  
}
/* react Not a pure module */
