// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Css from "@emotion/css";

var navbarContainer = Css.css("\n  padding: 1rem 2rem;\n  display: flex;\n  background: black;\n  flex-direction: row;\n  align-items: center;\n  justify-content: space-between;\n  ");

var navTitleStyle = Css.css("\n  font-weight: bold;\n  font-size: 32px;\n  color: white;\n");

var navButtonWrapper = Css.css("\n  gap: 12px;\n  display: flex;\n  justify-content: space-between;\n  ");

var navButton = Css.css("\n  &:hover {\n    cursor: pointer;\n  }\n  ");

export {
  navbarContainer ,
  navTitleStyle ,
  navButtonWrapper ,
  navButton ,
  
}
/* navbarContainer Not a pure module */
